[build]
  command = "npm install && npm run build"
  publish = "dist"
  node_version = "18"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle API requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "npm run dev"
  port = 4000
  targetPort = 4001
  functions = "netlify/functions"

# Primary domain configuration
[context.production]
  publish = "dist"
  command = "npm run build"
